### ISSUE TITLE
head of empty list

### ISSUE THREAD

**Issue by Verneri** [xuwei-k/sbt-class-diagram#2]
I tried to use the plugin and it resulted in:

```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:337)
	at scala.collection.immutable.Nil$.head(List.scala:334)
	at diagram.Plugin$$anonfun$2$$anonfun$apply$4$$anonfun$apply$5.apply(Plugin.scala:35)
	at diagram.Plugin$$anonfun$2$$anonfun$apply$4$$anonfun$apply$5.apply(Plugin.scala:33)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using sbt version 0.13.7

what am i missing?

**Comment by hugocf** [comment]
Same here. Still happening on both the stable version (1.7) and snapshot (1.8-SNAPSHOT) versions :(

**Comment by sumkincpp** [comment]
Same here, sbt version 0.13.8

**Comment by anselmevignon** [comment]
You need to add the name of the class you want to see plotted.

e.g. 
>scalaDiagram my.package.MyClass

**Comment by vreuter** [comment]
> e.g.
> 
> > scalaDiagram my.package.MyClass

For me only `classDiagram`, rather than `scalaDiagram`, works.

**Comment by frankzinner** [comment]
I'm missing support for Objects - it seems only classes are working.
